My1.15 adds
JavaPOSWorkingGroup/javapos-contracts pull request #13
Opened 2022-04-10 08:10 UTC by mjpcger

...service115 and ...control115 interfaces added for all devices. Additional properties and methods to really support UPOS 1.14.1 and 1.15 are part of the new interfaces.

2022-04-10 08:31 UTC, mjpcger commented
Further remark:
Constants added in UPOS 1.14.1 and UPOS 1.15 have been added to FiscalPrinterConst and ElectronicValueRWConst, too.

2022-04-10 17:34 UTC, kuniss commented
@mjpcger, please open a separate PR for the ElectronicRW constant correction for issue #14. 
Even if this seems to be more work, we need to have the changes reproducible for that public repo. The constant corrections are not related to 1.15!
Just make a branch for your issue, copy the changes to there and provide a 2nd PR.
Revert the corresponding changes here at that PR.
Thanks in advance!

2022-04-21 16:22 UTC, kuniss requested changes
Well done!
You even figured out the constants I missed when I wrongly closed #8. 👍

Please check my comments: There is one significant set method missing in EVRW. And some improvements I proposed.

However, there is also one major point, we have to consider: the OPOS "working group" is maintaining there own reference implementation on Github: https://github.com/kunif/OPOS-CCO.
We have to ensure, for OPOS/JavaPOS interoperability, that the constant values here and there are equal! 
The OPOS guys were faster than us. So, we have to follow their chosen values... 
I have added corresponding comments in your PR (with a link to their source files for a fast look up) where the constants have to be adapted .

Thanks again, for all your work! 🥇

2022-04-21 16:22 UTC, kuniss commented on src/main/java/jpos/services/BeltService115.java
> +import jpos.*;
The imports are redundant and probably will cause a compiler warning. I would prefer, you remove them (in all 1.15 service interfaces).

2022-04-21 21:15 UTC, mjpcger commented
Changes made as requested.
**Remark**: EVWR methods updateKey and activateService use the same Object[] type instead of Object for parameter obj as I used in the previous version. This is the reason why I did it wrong. Perhaps this should be corrected as well.

2022-04-21 21:17 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> -//////////////////////////////////////////////////////////////////////
Should be the case now.

2022-04-21 21:17 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> +  public static final int EVRW_PAYMENT_LUMP                   = 1; // Added in release 1.15
Checked and changed for all new EVWR values.

2022-04-21 21:18 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> +  public static final int EVRW_ST_UNSPECIFIED          = 5; // Added in release 1.14.1
Done

2022-04-21 21:18 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> +  public static final int EVRW_TRANSACTION_SALES          = 1; // Added in release 1.15
Done.

2022-04-21 21:23 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> +  public static final int EVRW_AD_OTHERS         = 99; // Added in release 1.14.1
Done (value changed to 3, no change issue.

2022-04-21 21:23 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
>    // "accessLog" Method: "Type" Parameter Constants
Done.

2022-04-21 21:24 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWConst.java
> +  public static final int EVRW_TE_NOTIFY_PROGRESS_1_TO_100          = 22; // Added in release 1.14.1
Checked. Seems to be good for me.

2022-04-21 21:25 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +    public int getPaymentMedia() throws JposException;
Declaration added.

2022-04-21 21:29 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
Done. Remark: The methods updateKey and activateService, specified in EVWR, version 1.12, use Object[] insted of Object as well, that's the reason why I did it the same way...

2022-04-21 21:30 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                                  Object[] object) throws JposException; // 1.14.1
Done, see above.

2022-04-21 21:30 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                                    Object[] object) throws JposException; // 1.14.1
Done, see above.

2022-04-21 21:30 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                                    Object[] object) throws JposException; // 1.14.1
Done, see above.

2022-04-21 21:31 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                                   Object[] object) throws JposException; // 1.14.1
Done, see above.

2022-04-21 21:31 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
Done, see above.

2022-04-21 21:32 UTC, mjpcger commented on src/main/java/jpos/FiscalPrinterConst.java
> +    public static final int FPTR_S_JOURNAL_SLIP = FPTR_S_JOURNAL | FPTR_S_SLIP; // 1.15
Comment deleted because I don't know the version when these constants have been added to UPOS.

2022-04-21 21:33 UTC, mjpcger commented on src/main/java/jpos/FiscalPrinterConst.java
> +    public static final int FPTR_AC_SEK                      =  13; // 1.15
Comment changed as suggested.

2022-04-21 21:34 UTC, mjpcger commented on src/main/java/jpos/FiscalPrinterConst.java
> +    public static final int FPTR_CC_SWEDEN                   = 0x00000800; // 1.15
Comment changed as suggested.

2022-04-21 21:46 UTC, kuniss commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
OK, that's an argument! I didn't see that...

Let's rethink this! It may be better to be consistent within the EVRW device category than to be consistent to `directIO()`, a base method.  -- Local consistency over global consistency. :smile: 
Both approaches are formally right. `Object[]` is slightly better in general (signaling an out parameter through `[]`). 
Java in general is worse in regard to out parameters! :nerd_face:  

What do you think, @mjpcger? Should we switch back to your first approach, using `Object[]`?

2022-04-21 21:46 UTC, mjpcger commented on src/main/java/jpos/BeltControl115.java
> +import jpos.events.*;
Removed unused imports for ...Control115 and ...Service115.

2022-04-21 21:46 UTC, mjpcger commented on src/main/java/jpos/services/BeltService115.java
> +import jpos.*;
Removed unused imports for ...Control115 and ...Service115.

2022-04-28 08:39 UTC, kuniss commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
@mjpcger, what do you think? Maybe, we should go with your approach? Seems more consistent to me after your argument...

2022-04-28 08:48 UTC, kuniss commented on src/main/java/jpos/ElectronicValueRWConst.java
> -//////////////////////////////////////////////////////////////////////
Still shows up as changed. But don't be bothered further. I checked the text. It's not altered, so we can live with that.
I will try to get it unchanged when merging.

2022-05-15 20:10 UTC, kuniss commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
Hey @mjpcger, all OK? 
Did you see my last comment with the questions?

2022-05-17 19:24 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
Sorry, I did not see the question up to now.

I think the UPOS specification is clear: For Object parameters, even if mutable or not, type Object shall be used, therefore using Object instead of Object[] would be more UPOS compliant.
However, the current implementations in EVWR uses Object[] instead of Object for mutable parameters. I think this ensures that given parameters can be changed completely. For example, if the Object parameter is an Integer or a String, passing it directly makes it impossible to get the changed value back. Conclusion: If mutable parameters are of basic type, they must always be passed in an array. For complex types, non-array type mutable parameters can be useful if only object properties must be changed and not the object itself.
I think an addition to the UPOS specification is the best way:
In Annex B, B13 Java, mutable parameters of _type_ can be passed as _Object_, if only properties or object status shall be changeable. In all other cases, mutable parameters of _type_ must be passed as _Object[1]_. 

Therefore, for EVWR, we should let it Object[] instead of Object because all other EVWR methods using mutable Object parameters use currently Object[] instead of Object and it cannot be ruled out that objects will normally have to be completely replaced (e.g. because these objects are normally strings or numerical values). This is different to directIO, where in many cases the object value will never be changed.

2022-05-18 18:57 UTC, kuniss commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
I agree!
Do you change it back to your original implementation then?

Sorry for having caused this additional effort!

2022-05-19 08:18 UTC, mjpcger commented
I'll do it asap.

Am 18.05.22 um 20:57 schrieb Denis Kuniß:
>
> ***@***.**** commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In src/main/java/jpos/ElectronicValueRWControl115.java
> <https://github.com/JavaPOSWorkingGroup/javapos-contracts/pull/13#discussion_r876242803>:
>
> > +    public String getDailyLog() throws JposException;
> +    public int getPaymentCondition() throws JposException;
> +    public String getPaymentDetail() throws JposException;
> +    public int getPaymentMedia() throws JposException;
> +    public String getSlipNumber() throws JposException;
> +    public String getTransactionNumber() throws JposException;
> +    public int getTransactionType() throws JposException;
> +    public int getServiceType() throws JposException; // 1.14.1
> +
> +    // Methods
> +    public void accessDailyLog(int sequenceNumber,
> +                               int type,
> +                               int timeout) throws JposException;
> +    public void accessData(int dataType,
> +                           int[] data,
> +                           Object[] object) throws JposException; // 1.14.1
>
> I agree!
> Do you change it back to your original implementation then?
>
> Sorry for having caused this additional effort!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JavaPOSWorkingGroup/javapos-contracts/pull/13#discussion_r876242803>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI7UND6JBIQWDO6PDNC3ENLVKU4SVANCNFSM5TAPEPGA>.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-19 11:25 UTC, mjpcger commented on src/main/java/jpos/ElectronicValueRWControl115.java
> +                           Object[] object) throws JposException; // 1.14.1
I did it, see end of the pull request

2022-05-27 18:35 UTC, merged